version: '3.6'

services:
  server:
    image: ${IMAGE_NAME:-localhost/echo-server-tcp}:${VERSION:-latest}
    build: .
    volumes:
      - ./echo-server.php:/var/www/html/echo-server.php
    command: php echo-server.php
    environment:
      LISTEN_PORT: 9900
    ports:
      - "9900:9900"
